// <auto-generated />
using Lab19WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab19WebApi.Migrations
{
    [DbContext(typeof(TodoListDBContext))]
    [Migration("20181103151216_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab19WebApi.Models.Todo", b =>
                {
                    b.Property<int>("TodoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details");

                    b.Property<bool>("Finished");

                    b.Property<string>("Task");

                    b.Property<int>("TodolistId");

                    b.HasKey("TodoId");

                    b.HasIndex("TodolistId");

                    b.ToTable("Todos");

                    b.HasData(
                        new { TodoId = 1, Finished = false, Task = "Make DB migration", TodolistId = 1 },
                        new { TodoId = 2, Finished = false, Task = "Implement controllers", TodolistId = 1 },
                        new { TodoId = 3, Finished = false, Task = "Write tests", TodolistId = 1 },
                        new { TodoId = 4, Finished = false, Task = "Play with kids", TodolistId = 2 }
                    );
                });

            modelBuilder.Entity("Lab19WebApi.Models.Todolist", b =>
                {
                    b.Property<int>("TodolistId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("TodolistId");

                    b.ToTable("Todolists");

                    b.HasData(
                        new { TodolistId = 1, Name = "Lab19" },
                        new { TodolistId = 2, Name = "Family" }
                    );
                });

            modelBuilder.Entity("Lab19WebApi.Models.Todo", b =>
                {
                    b.HasOne("Lab19WebApi.Models.Todolist", "Todolist")
                        .WithMany("Todos")
                        .HasForeignKey("TodolistId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
